#!/bin/bash
set -e

echo "=========================================="
echo "  Starting Balbescraft Server Setup"
echo "=========================================="

# Default memory settings
MIN_RAM=${MIN_RAM:-2G}
MAX_RAM=${MAX_RAM:-10G}

echo "Memory: ${MIN_RAM} - ${MAX_RAM}"

# Accept EULA
echo "eula=true" > /server/eula.txt

# Generate server.properties from environment variables
generate_server_properties() {
    echo "Generating server.properties..."
    cat > /server/server.properties << EOF
# Minecraft Server Properties
# Auto-generated by startup script

# Network
server-port=25565
server-ip=
network-compression-threshold=256
max-players=${MAX_PLAYERS:-20}

# World Settings
level-name=world
level-seed=${SEED:-}
level-type=minecraft\:normal
generator-settings={}
generate-structures=true

# Game Settings
gamemode=${GAMEMODE:-survival}
difficulty=${DIFFICULTY:-normal}
hardcore=false
pvp=true
allow-flight=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
force-gamemode=false

# Online Mode (false for offline/cracked clients)
online-mode=false
prevent-proxy-connections=false
enforce-secure-profile=false

# Whitelist
white-list=true
enforce-whitelist=true

# Performance
view-distance=${VIEW_DISTANCE:-10}
simulation-distance=${SIMULATION_DISTANCE:-10}
max-tick-time=60000
entity-broadcast-range-percentage=100

# Server Info
motd=${MOTD:-A Minecraft Server}
enable-status=true
hide-online-players=false

# Security
spawn-protection=16
max-world-size=29999984
allow-nether=true

# RCON
enable-rcon=false
rcon.password=
rcon.port=25575
broadcast-rcon-to-ops=true

# Query
enable-query=false
query.port=25565

# Misc
op-permission-level=4
function-permission-level=2
player-idle-timeout=0
rate-limit=0
enable-command-block=true
sync-chunk-writes=true
require-resource-pack=false
resource-pack=
resource-pack-prompt=
resource-pack-sha1=
text-filtering-config=
log-ips=true
EOF
}

# Setup datapacks
setup_datapacks() {
    echo "Setting up datapacks..."
    mkdir -p /server/world/datapacks

    if [ -d "/server/datapacks" ] && [ "$(ls -A /server/datapacks 2>/dev/null)" ]; then
        for datapack in /server/datapacks/*; do
            if [ -e "$datapack" ] && [ "$(basename "$datapack")" != ".gitkeep" ]; then
                datapack_name=$(basename "$datapack")
                echo "  Installing: ${datapack_name}"
                cp -r "$datapack" "/server/world/datapacks/" 2>/dev/null || true
            fi
        done
    else
        echo "  No datapacks found"
    fi
}

# Setup whitelist
setup_whitelist() {
    if [ ! -f "/server/whitelist.json" ]; then
        echo "[]" > /server/whitelist.json
    fi
}

# Setup ops
setup_ops() {
    if [ ! -f "/server/ops.json" ]; then
        echo "[]" > /server/ops.json
    fi
}

# Setup banned lists
setup_bans() {
    if [ ! -f "/server/banned-players.json" ]; then
        echo "[]" > /server/banned-players.json
    fi
    if [ ! -f "/server/banned-ips.json" ]; then
        echo "[]" > /server/banned-ips.json
    fi
}

# Create Paper configuration for vanilla-like experience
setup_paper_config() {
    echo "Setting up Paper configuration..."
    mkdir -p /server/config

    cat > /server/config/paper-global.yml << 'EOF'
_version: 29
messages:
  no-permission: "I'm sorry, but you do not have permission to perform this command."
  kick:
    connection-throttle: "Connection throttled! Please wait before reconnecting."
misc:
  max-joins-per-tick: 5
  fix-entity-position-desync: true
proxies:
  velocity:
    enabled: false
    online-mode: false
    secret: ""
unsupported-settings:
  allow-piston-duplication: false
  allow-permanent-block-break-exploits: false
  perform-username-validation: true
EOF

    cat > /server/config/paper-world-defaults.yml << 'EOF'
_version: 31
anticheat:
  anti-xray:
    enabled: false
entities:
  behavior:
    pillager-patrols:
      disable: false
environment:
  treasure-maps:
    enabled: true
    find-already-discovered:
      loot-tables: default
      villager-trade: false
fixes:
  fix-curing-zombie-villager-discount-exploit: true
misc:
  redstone-implementation: VANILLA
spawn:
  keep-spawn-loaded: true
EOF
}

# Setup spigot.yml
setup_spigot_config() {
    echo "Setting up Spigot configuration..."
    cat > /server/spigot.yml << 'EOF'
config-version: 12
settings:
  debug: false
  bungeecord: false
  timeout-time: 60
  restart-on-crash: true
messages:
  whitelist: "You are not whitelisted on this server!"
  unknown-command: "Unknown command. Type \"/help\" for help."
  server-full: "The server is full!"
commands:
  silent-commandblock-console: false
  log: true
  tab-complete: 0
world-settings:
  default:
    verbose: false
    merge-radius:
      item: 2.5
      exp: 3.0
    item-despawn-rate: 6000
    mob-spawn-range: 8
    nerf-spawner-mobs: false
    entity-activation-range:
      animals: 32
      monsters: 32
      raiders: 48
      misc: 16
      water: 16
      villagers: 32
      flying-monsters: 32
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
EOF
}

# Setup bukkit.yml
setup_bukkit_config() {
    echo "Setting up Bukkit configuration..."
    cat > /server/bukkit.yml << 'EOF'
settings:
  allow-end: true
  warn-on-overload: true
  permissions-file: permissions.yml
  shutdown-message: "Server closed"
spawn-limits:
  monsters: 70
  animals: 10
  water-animals: 5
  water-ambient: 20
  ambient: 15
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: 1
  autosave: 6000
EOF
}

# Main setup
echo ""
echo "Starting server setup..."

generate_server_properties
setup_paper_config
setup_spigot_config
setup_bukkit_config
setup_datapacks
setup_whitelist
setup_ops
setup_bans

echo ""
echo "=========================================="
echo "  Server configuration complete!"
echo "  Starting Minecraft server..."
echo "=========================================="
echo ""
echo "Memory allocation: -Xms${MIN_RAM} -Xmx${MAX_RAM}"
echo ""

# List plugins if any
if [ -d "/server/plugins" ] && [ "$(ls -A /server/plugins/*.jar 2>/dev/null)" ]; then
    echo "Plugins found:"
    ls /server/plugins/*.jar 2>/dev/null | while read jar; do
        echo "  - $(basename "$jar")"
    done
    echo ""
fi

# Start the server with optimized JVM flags (Aikar's flags)
exec java \
    -Xms${MIN_RAM} \
    -Xmx${MAX_RAM} \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:+AlwaysPreTouch \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dusing.aikars.flags=https://mcflags.emc.gs \
    -Daikars.new.flags=true \
    -jar /server/paper.jar \
    --nogui
